### ISSUE TITLE
Support Websocket

### ISSUE THREAD

**Issue by rickyhan** [aloysius-pgast/crypto-exchanges-gateway#1]
Hello,

Nice project. I think this has great potential. Putting everything in one place really simplifies the development process.

In the future, can you please also enable websockets for orderbook updates? I know `node.bittrex.api` has good support for it. For a working example, please take a look at my code: https://github.com/rickyhan/bittrex-orderbook-importer

**Comment by aloysius-pgast** [comment]
Thanks. You mean allow to relay WS connections through the gateway ? Right know i'm more focused on providing a REST API to let people build services from it. Will keep it in mind for the future :)

**Comment by rickyhan** [comment]
I am working on a pull request.

**Comment by aloysius-pgast** [comment]
Hi. Quick update. I should be able to push a first version with WS support end of the week / beginning of next one.

**Comment by aloysius-pgast** [comment]
Hi. Finally got a version with WS support. Could you please give it a try when you have some time ?
It's only on branch https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop for now. Behaviour is expected to be consistent across all 3 exchanges with support for following events :

* tickers
* order books
* trades

Also :
* WS endpoint ws://127.0.0.1:8001 should be available (REST endpoint remains http://127.0.0.1)
* Documentation for endpoints & RPC protocol is available under https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop/doc/ws
* WS examples are available under https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop/examples/ws

**Comment by aloysius-pgast** [comment]
Just uploaded an npm package to make it easier to interact with the RPC endpoint
https://www.npmjs.com/package/crypto-exchanges-ws-client

**Comment by aloysius-pgast** [comment]
Integration done in [develop branch](https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop) and included in [demo](https://mpe-demo.crazyme.net/)
