### ISSUE TITLE
npm install ERROR

### ISSUE THREAD

**Issue by mauphung** [aloysius-pgast/crypto-exchanges-gateway#115]
When I run npm install, I got a following error.
2 info using npm@6.14.11
3 info using node@v14.16.0

8271 error sqlite3@4.1.0 install: `node-pre-gyp install --fallback-to-build`
8271 error Exit status 1

Please help me to install crypto-exchanges-gateway

**Comment by mauphung** [comment]
I think this issue comes from latest version of sqlite3. I try npm install sqlite3@4.1.1 and use it. It works OK for me

**Comment by aloysius-pgast** [comment]
Hi. Which OS are you running ? With *node* `4.15.1` and *npm* `6.14.8`, `npm install` runs fine.
I'll check with *node* `14.16.0` to see if it makes any difference

**Comment by aloysius-pgast** [comment]
Same with *node* `14.16.0` : `sqlite3` builds correctly (except for a few warnings)
