### ISSUE TITLE
Add cfg.exchanges.kucoin.password into environment variables

### ISSUE THREAD

**Issue by whitebone123** [aloysius-pgast/crypto-exchanges-gateway#123]
Hi, is it possible to add 'cfg.exchanges.kucoin.password' into environment variables? Since it's required for Kucoin module.

**Comment by aloysius-pgast** [comment]
Hi. Thanks for the feedback. Should work on it in the next few days

**Comment by aloysius-pgast** [comment]
Should be good in version https://github.com/aloysius-pgast/crypto-exchanges-gateway/releases/tag/1.10.2

**Comment by whitebone123** [comment]
awesome
