### ISSUE TITLE
Tiny issue of the doc

### ISSUE THREAD

**Issue by whitebone123** [aloysius-pgast/crypto-exchanges-gateway#127]
Just a tiny issue of the doc/pushover/notificaiton.adoc. Is 'message' in below table a mandatory parameter rather than a column title?
![image](https://user-images.githubusercontent.com/81951739/134770989-c9049c2f-1b20-402f-a138-32dd64515909.png)

**Comment by aloysius-pgast** [comment]
Thanks for feedback !
