### ISSUE TITLE
Completed orders filled amount

### ISSUE THREAD

**Issue by pcartwright81** [aloysius-pgast/crypto-exchanges-gateway#19]
The amount shown is the order amount.  Would it be possible to add a column for the filled amount?

**Comment by aloysius-pgast** [comment]
Hi @pcartwright81. You mean in the UI, _My Orders_ view ? Is-it when using the demo or with your own instance ? Also, do you see this for a specific exchange ?
Thanks

**Comment by pcartwright81** [comment]
Own instance and UI orders view on Bittrex.
In the api it is Quantity - QuantityRemaining

**Comment by aloysius-pgast** [comment]
Ok. Do you think you could provide an example of what is displayed and what you would expect, to make things clearer ?

**Comment by pcartwright81** [comment]
This is what is displayed on Bittrex under quantity filled.
![bittrex data](https://user-images.githubusercontent.com/2352477/33438028-4db424fc-d5af-11e7-8672-37925c0dfc6f.PNG)
crypto-exchanges-gateway ui it displays the order total I believe.  
![personal exchange](https://user-images.githubusercontent.com/2352477/33438030-4dce2c08-d5af-11e7-8a95-20840f35eedb.PNG)

If an order is cancelled the quantity remaining is a static value.

**Comment by aloysius-pgast** [comment]
Thanks for the explanation. I just commited on the develop branch to fix this.

**Comment by pcartwright81** [comment]
Awesome thank you.  Tested and working.
