### ISSUE TITLE
enable tradingview widget draw toolbar

### ISSUE THREAD

**Issue by toneffectory** [aloysius-pgast/crypto-exchanges-gateway#23]
Would be great if you could enable the tradingview widget draw toolbar. 

If you agree, you can add this option:
`  "hide_side_toolbar": false,`

to:

` new TradingView.widget({`

in file ui/src/components/CandleSticks/CandleSticks.js

**Comment by aloysius-pgast** [comment]
HI. Thanks for the suggestion, I'll push it soon.

**Comment by aloysius-pgast** [comment]
Hi. Change was pushed to [https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop](develop) branch
