### ISSUE TITLE
one click withdrawal on balance page

### ISSUE THREAD

**Issue by pipinoloco** [aloysius-pgast/crypto-exchanges-gateway#27]
A cool feature is one click withdrawal on balance page, for example you click on XRP and sends the XRP from Binance to Poloniex, it would be cool to cross the coins from exchange to another with just one click.

**Comment by aloysius-pgast** [comment]
Hi. Unfortunately, withdrawal is not something I'm willing to dig into as from my experience this is where problems can occur :

- invalid withdrawal address (sending ETC to ETH address for example)
- invalid amount (thinking about NEO where you can only transfer integer amount)
- how to follow the status of the transaction

Better keep doing it directly on the exchange :)
