### ISSUE TITLE
calculate open orders value

### ISSUE THREAD

**Issue by pipinoloco** [aloysius-pgast/crypto-exchanges-gateway#28]
to have a better total in the account, example i have 10 open orders with a market value of 0.10 ether, adding that to the balance as total value of holdings, like Poloniex have in the history page.

**Comment by aloysius-pgast** [comment]
Not sure what you mean. The balance should reflect what you currently have. Care to give an example of what you propose, with the difference between what currently exists ?
Thanks

**Comment by pipinoloco** [comment]
if i have 1000 MANA-ETH on orders waiting to be sold, adding the current value of MANA (market price) in ethers. if it worth 0.085 ether adding that to the ether balance. every time the market price changes my current balance in ether will change

**Comment by aloysius-pgast** [comment]
The balance should reflect what you currently have. So if you have :
* 1 ETH
* 1000 MANA you're trying to sell for ETH
Your balance should be :
* 1 ETH
* 1000 MANA
Updating the ETH balance because of the open MANA-ETH order would be quite confusing imho. What would be the MANA balance then ? 0 ?

**Comment by pipinoloco** [comment]
i know, a good tip is to put "open orders value" (with market price), below the open orders panel could be.
current price is retrieved from the current price on each market, so if MANA is 0.10 open value and then 0.08 the open value will change. 
This is good to know how are you performing on trading and what is the amount of open value, in USD and in BTC or ETH.

**Comment by aloysius-pgast** [comment]
What I could do is allow user to choose between multiple fiat currencies or crypto currencies in portfolio view. It is currently displayed in $ only but it should be possible to display it in EUR, BTC, ETH (ie: whatever crypto currency is supported by coinmarketcap)

**Comment by pipinoloco** [comment]
yes, some sort of portfolio view.


Enviado desde Outlook<http://aka.ms/weboutlook>

________________________________
De: aloysius-pgast <notifications@github.com>
Enviado: viernes, 02 de febrero de 2018 02:18 p.m.
Para: aloysius-pgast/crypto-exchanges-gateway
Cc: pipinoloco; Author
Asunto: Re: [aloysius-pgast/crypto-exchanges-gateway] calculate open orders value (#28)


What I could do is allow user to choose between multiple fiat currencies or crypto currencies in portfolio view. It is currently displayed in $ only but it should be possible to display it in EUR, BTC, ETH (ie: whatever crypto currency is supported by coinmarketcap)
