### ISSUE TITLE
Crypto Portfolio add-on

### ISSUE THREAD

**Issue by tymiles003** [aloysius-pgast/crypto-exchanges-gateway#30]
Team,
Is it possible to add a portfolio that display your holdings with profits/losses with trends for the coin purchased or sold.
Thanks

**Comment by pipinoloco** [comment]
i want that also

**Comment by aloysius-pgast** [comment]
Hi

If you try the version on _develop_ branch, there is a portfolio view integrated. It will display all coins across all exchanges. 

It does not display any profit/loss information (and it’s not planned for now)
