### ISSUE TITLE
Last Trades on Order Book Buy/Sell Colors Wrong - Binance

### ISSUE THREAD

**Issue by insanid** [aloysius-pgast/crypto-exchanges-gateway#31]
When opening the Order Book the Last Trades section is showing the wrong colors. Buys are showing as red instead of green and vice versa.

This is on the development version cloned as of 2/2/2018.

**Comment by aloysius-pgast** [comment]
Thanks for the feedback, i’ll look into this

**Comment by aloysius-pgast** [comment]
Hi. Seems like Binance API is inconsistent with what is returned. Or I didn't understand it correctly :)
Anyway, it's fixed in [develop](https://github.com/aloysius-pgast/crypto-exchanges-gateway/tree/develop) branch.
