### ISSUE TITLE
error when building UI on Ubuntu with OPENVZ

### ISSUE THREAD

**Issue by pipinoloco** [aloysius-pgast/crypto-exchanges-gateway#36]
![ui error](https://user-images.githubusercontent.com/29177517/35813424-58716402-0a72-11e8-91a1-7924b096db72.JPG)

**Comment by pipinoloco** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v9.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle crypto-exchanges-gateway-ui@1.0.0~prebuild: crypto-exchanges-gateway-ui@1.0.0
6 info lifecycle crypto-exchanges-gateway-ui@1.0.0~build: crypto-exchanges-gateway-ui@1.0.0
7 verbose lifecycle crypto-exchanges-gateway-ui@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle crypto-exchanges-gateway-ui@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/cry$
9 verbose lifecycle crypto-exchanges-gateway-ui@1.0.0~build: CWD: /root/crypto-exchanges-gateway/ui
10 silly lifecycle crypto-exchanges-gateway-ui@1.0.0~build: Args: [ '-c', 'webpack --progress' ]
11 silly lifecycle crypto-exchanges-gateway-ui@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle crypto-exchanges-gateway-ui@1.0.0~build: Failed to exec build script
13 verbose stack Error: crypto-exchanges-gateway-ui@1.0.0 build: `webpack --progress`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid crypto-exchanges-gateway-ui@1.0.0
15 verbose cwd /root/crypto-exchanges-gateway/ui
16 verbose Linux 2.6.32-042stab120.6
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.4.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 137
22 error crypto-exchanges-gateway-ui@1.0.0 build: `webpack --progress`
22 error Exit status 137

**Comment by pipinoloco** [comment]
on a different server with debian OS was perfect.

**Comment by aloysius-pgast** [comment]
I noticed that in first screenshot you're doing : 

```
npm install -g npm@latest`
npm run clean && npm run build
```
 Instead of

```
npm install -g webpack && npm install
npm run clean && npm run build
```
Error might be because _webpack_ was not installed. Can you try again with above ?

**Comment by pipinoloco** [comment]
the problem is in webpack here
![webpack error](https://user-images.githubusercontent.com/29177517/35824709-796db492-0a92-11e8-9622-d9537fcb39d9.JPG)

**Comment by aloysius-pgast** [comment]
Ok, so it's resolved after running correct command, right ?

**Comment by pipinoloco** [comment]
yes
