### ISSUE TITLE
does developer branch allows trading?

### ISSUE THREAD

**Issue by pipinoloco** [aloysius-pgast/crypto-exchanges-gateway#38]
i can-t access mytrades on developer branch edition, whan i am making wrong?

**Comment by aloysius-pgast** [comment]
What do you mean "can't access ?"

**Comment by pipinoloco** [comment]
startup is the same, i don't have access to Balance and MyOrders, before Binance outage everything was smooth.

**Comment by aloysius-pgast** [comment]
You mean there is no entry in UI or no results returned ?

**Comment by aloysius-pgast** [comment]
Do you still have problem ? Another user had similar problem in https://github.com/aloysius-pgast/crypto-exchanges-gateway/issues/39 and it was a network pb on Binance side
