### ISSUE TITLE
Binance stopped working

### ISSUE THREAD

**Issue by tymiles003** [aloysius-pgast/crypto-exchanges-gateway#39]
Team,
I have installed the developer version and it was working fine, but now binance stopped working, bittrex and poloniex are still working properly, any suggestions?
Thanks

**Comment by aloysius-pgast** [comment]
Hi
Do you have problem for a view in particular ? Any logs in the console ?

**Comment by tymiles003** [comment]
The issue was with binance and not the application.
Thanks

**Comment by aloysius-pgast** [comment]
Ok, that's what I was about to suggest. I noticed that sometimes I wasn't able to access Binance website on https://www.binance.com/ but https://us.binance.com was working. They probably had some access problems in some regions. I'll check with the maintainer of Binance module to see if he could make the url as an option
