### ISSUE TITLE
User Authentication 

### ISSUE THREAD

**Issue by tymiles003** [aloysius-pgast/crypto-exchanges-gateway#40]
Is there a way to add user authentication or a password to lock down of the application? I would like to have so form of security that would allow me run the instance non-stop, is this possible?

**Comment by aloysius-pgast** [comment]
In config.json you can :
* define an API key : all requests sent to gateway without correct value in _apikey_ header will be refused
* restrict access to only some IP addresses

Check https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/master/doc/config.adoc for a list of all config parameters
