### ISSUE TITLE
Compare with ccxt

### ISSUE THREAD

**Issue by millette** [aloysius-pgast/crypto-exchanges-gateway#5]
This project seems very similar to [ccxt](https://github.com/kroitor/ccxt) - have you tried collaborating?

**Comment by aloysius-pgast** [comment]
Hi. I didn't know about CCXT before. I found a few other similar projects but I have to say CCXT really did an amazing job of integrating all those exchanges.  Main difference I see is the software coupling. While CCXT aims at providing a library, I wanted to offer an http gateway as an independant service to be used by any REST client (so virtually any language). Thanks for the link, I'll keep an eye on CCXT !

**Comment by millette** [comment]
Glad you appreciate the link. I wish you well :-)
