### ISSUE TITLE
Klines for exchanges that only have a trades websocket?

### ISSUE THREAD

**Issue by tiagosiebler** [aloysius-pgast/crypto-exchanges-gateway#77]
Does this support building klines for exchanges that only provide raw trades (e.g bitstamp)? Curious if this can help bridge the gap.

**Comment by aloysius-pgast** [comment]
Hi. Unfortunately, klines are only available if supported by exchange (there is no support for building klines from raw trades)

**Comment by tiagosiebler** [comment]
Thanks, if you'd consider it, it'd make a very very VERY valuable enhancement for this service. If not, feel free to close this issue.

**Comment by aloysius-pgast** [comment]
You’re talking about emitting real-time klines from trades over ws only (ie: no history)?

**Comment by tiagosiebler** [comment]
Yes, exactly. The binance kline websockets give an example of what I'd love the result of this to be.

**Comment by aloysius-pgast** [comment]
Since bitstamp REST API allows to retrieve all trades of last 24h, it should be possible to use it in combination with ws trades to build klines from 1m to 1d intervals once bitstamp support has been added to the gateway using ccxt api

**Comment by aloysius-pgast** [comment]
Closing this since this repo is almost dead
