### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by Gabri** [aloysius-pgast/crypto-exchanges-gateway#78]
Hello,
I'm trying using this interestng gateway. I'm using just Binance and I'm interested to WS klines only at the moment.
When my bot start using some pairs and, for every pairs, 3 or 4 timeframes I get this from the gateway log (with less combinations no warning at the moment):

`(node:4383) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ticker listeners added. Use emitter.setMaxListeners() to increase limit
(node:4383) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 orderBook listeners added. Use emitter.setMaxListeners() to increase limit
(node:4383) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 orderBookUpdate listeners added. Use emitter.setMaxListeners() to increase limit
(node:4383) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 trades listeners added. Use emitter.setMaxListeners() to increase limit
(node:4383) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 kline listeners added. Use emitter.setMaxListeners() to increase limit
`

Threre is something that I can set on configuration to avoid eventual problem of leak memory?

Thanks in advance

**Comment by aloysius-pgast** [comment]
Hi

Could you provide informations regarding gateway version, nodejs version and OS and provide sample code for the client part ?

Thanks

**Comment by Gabri** [comment]
Hi,
OS : Linux 64 - kernel 4.19 (Manjaro 18.0.4, Arch based)
Nodejs : 9.9.0 - I'm using this version (via nvm) for the gateway otherwise I have problems with module sqlite3 (the gateway doesn't start)
crypto-exchanges-gateway : branch master, latest (i think 1.7.11 from changelog)

Some code:
```
for (let symbol of this.symbols) {
candleEmitter[symbol] = new CandleStreamCryptoExchangeGatewayEmitter(symbol, this.timeframes, this.sleepLiveData, this.exchangeName);
	for (let timeframe of this.timeframes) {
		const candleListenerEventName = 'candle_' + symbol + '-' + timeframe
		candleEmitter[symbol].on(candleListenerEventName, (newCandle) => {
			this.candles[symbol][timeframe].push(newCandle)
			setImmediate(async () => {
				await this.strategy.run({ symbol, ticks: this.candles[symbol][timeframe], timeframe, time: newCandle.startTime })
			});
		});
	}
	candleEmitter[symbol].produceCanles()
}
```
And then in CandleStreamCryptoExchangeGatewayEmitter:
```
produceCandles() {
	this.timeframes.forEach(timeframe => {
		log.debug(`Connecting WS to CryExGateway for ${this.symbol} and TF ${timeframe}`)
		const ws = new WebSocket(`ws://127.0.0.1:8001/exchanges/${this.exchange}/klines/${this.symbolNormalized}?interval=${timeframe}`);
		ws.on('open', function open() {
			log.info(`OPEN Connecttion WSS to CrytoExchangeGateway to ${this.url}`)
		});
		ws.on('connection', function connection() {
			log.info('CONNECTION Connecttion WSS to CrytoExchangeGateway')
		});
		ws.on('ping', this.heartbeat);
		ws.on('close', function clear() {
			log.error(`CLOSED Connecttion WSS to CrytoExchangeGateway to ${this.url}`)
		});
		ws.on('message', function incoming(data) {
			const datajson = JSON.parse(data)
			if (datajson && datajson.d) {
				if (datajson.d.data.closed === false) {
					log.debug('WS CEG data but NOT closed Candle')
				}
				if (datajson.d.data.closed === true) {
					const evt_name = 'candle_' + _this.symbol + '-' + datajson.d.interval
					datajson.d.data['timeframe'] = datajson.d.interval
					_this.emit(evt_name, datajson.d.data);
				}
			}
		});
	});
}
```
I've got those warning when I run the bot with pairs: BTC/USDT ETH/USDT ADA/BTC BNB/BTC and timeframes 4h,1d,1w. With just one timeframe (1h) no warning.
Trying using more pairs and timeframes I've got WS kline **close** event sometimes suddenly after the connection.. I don't know why, i'll try again

Thanks!

**Comment by aloysius-pgast** [comment]
Thanks for the details, I’ll give it a look. Did you try with the RPC-based ws endpoint ? 

https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/master/doc/ws/endpoints.adoc#rpc-endpoint

**Comment by aloysius-pgast** [comment]
Hi. I pushed version `1.7.12` which should fix the warning problem. Since node 8.x, the *maximum number of listeners* for a given event default to `10`. When multiple *non-RPC* ws connections such as  `ws://127.0.0.1:8001/exchanges/binance/klines/USDT-BTC/?interval=4h` are opened, a new listener is added for each connection, and *after 10 connections a warning is displayed* (it can be safely ignored). 

Limit has been *increased to 100* in version `1.7.12`. While this should fix your problem, I recommend using *RPC* ws connections instead (npm package [crypto-exchanges-ws-client](https://www.npmjs.com/package/crypto-exchanges-ws-client) can be used). It allows to multiplex multiple events (tickers, klines ...) over a single ws connection. Here's an example

```
"use strict";
const WebSocket = require('crypto-exchanges-ws-client');

const pairs = ['USDT-BTC', 'USDT-ETH', 'BTC-ADA', 'BTC-BNB'];
const klinesInterval = ['4h', '1d', '1w'];

const uri = 'ws://127.0.0.1:8001';
const client = new WebSocket(uri);

client.on('connected', (data) => {
    console.log(`We connected/reconnected : ${JSON.stringify(data)}`);
});
// connection to gateway was lost (reconnection will be automatic)
client.on('disconnected', (data) => {
    console.log(`We've been disconnected : ${JSON.stringify(data)}`);
});

client.on('ready', (data) => {
    console.log(`Ready to subscribe : ${JSON.stringify(data)}`);
    for (let pair of pairs) {
        for (let interval of klinesInterval) {
            client.subscribeToKlines('binance', [pair], interval);
        }
    }
});

client.on('kline', (evt) => {
    console.log(evt);
});
```
Regarding the problem with the `sqlite3` module, could you provide more information ?

**Comment by aloysius-pgast** [comment]
Another option is to create a stream using the UI (see MyStreams menu entry). You can add define multiple subscriptions and then connecte to a single ws uri such as ˋws://127.0.0.1:8001/?sid=mystream.Test` to receive events

**Comment by Gabri** [comment]
Hello,

Thank you very much, super helpful informations! Surely I'll try RPC ws connection as you kindly shared!
I  haven't installed the UI (I run it on raspberry when the bot works), but I'll try the MyStreams as you suggest.

I had problems with sqlite3, I've seen a version update on last commit. I found the solution to my problem somewhere in stackoverflow where someone was talking about downgrading node to version 9. Maybe I could made a little mess in my pc because I have tried a lot of things including installing it as global.
Anyway if I start the gateway with node 10 I get:
```
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module '/mnt/workspace/ws/git/cry/crypto-exchanges-gateway/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/workspace/ws/git/cry/crypto-exchanges-gateway/node_modules/sqlite3/lib/sqlite3.js:4:15)
```
Using node 9.9.0 works... I don't remember exactly why, I had the problem some weeks ago

Thanks for all

**Comment by aloysius-pgast** [comment]
Hi. I did some tests with  *node* `node@v10.16.3` and *npm* `npm@6.9.0` under *Ubuntu* `18.04` and I reproduced the problem with *sqlite3*

1) Using *sqlite3* version `3.1.13` (version used in gateway version `1.7.11`)

Command `npm install` fails to install *sqlite3* module

```
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.16.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
...
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/app/node/node-v10.16.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

As a result it's not possible to start the gateway

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

2) Using *sqlite3* version `4.1.0` (version used in gateway version `1.7.12`)

Module installs correctly and gateway can be started (on both *x86_64* and *raspberry pi*)

**Comment by Gabri** [comment]
Thank you very much
