### ISSUE TITLE
Question: WS kline or polling history candles?

### ISSUE THREAD

**Issue by Gabri** [aloysius-pgast/crypto-exchanges-gateway#81]
Hello,

Just a question regarding the best approach on getting data form crypto exchange gateway.
My need is to get just close candles and when a new candle (close) trigger a stragegy is applied to the candles. I want to monitor some pairs (10-15) with different timeframes (3-4).
Is there sense to listen to WS RPC klines, currently discarding data for not closed klines, for higher timeframes?
1d o 1w or why not 1m ...maybe there is no sense to use websocket in this case, isn't it?
Above all because there could be disconnections ..and for 1w candles, for example, I could lose the closing data.
Maybe in this scenario WS is good for timeframes till 1d?

Thanks for your eventual suggestions

**Comment by aloysius-pgast** [comment]
Hi. If you don't want real-time candles and are only interested in *closed* one, REST API might be better (see https://github.com/aloysius-pgast/crypto-exchanges-gateway/blob/master/doc/exchanges/klines.adoc).

**Comment by Gabri** [comment]
Ok, thanks
