### ISSUE TITLE
Setting ports on docker command does not work

### ISSUE THREAD

**Issue by lolero** [aloysius-pgast/crypto-exchanges-gateway#84]
I would like to use local ports other than 8000 and 8001 for the http and ws servers of the docker container.

But when I run `docker run --rm -p 8100:8100 -p 8101:8101 --name ceg apendergast/crypto-exchanges-gateway`, the container starts but prints the following on the console.

```
1586176403316|WARN|HTTP server is alive on *:8000
1586176403317|WARN|WS server is alive on *:8001
```

**Comment by aloysius-pgast** [comment]
Sorry but this is not how docker works
