### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Luke-Small** [aloysius-pgast/crypto-exchanges-gateway#85]
Hey there, 
Im trying to get the gateway running im running into an error it says something like this: 

/home/usr/Downloads/crypto-exchanges-gateway-master/app/default-ccxt-client.js: 44
 this.ccxt = new ccxt[ccxtExchangeId](ccxtExchangeOpt); 

TypeError: ccxt[ccxtExchangeId] is not a constructor

I am just starting to breach more complicated codes such as this one, could someone help me?

**Comment by aloysius-pgast** [comment]
Hi. Which command did you run exactly ?

**Comment by Luke-Small** [comment]
This is the command and its given information(so the answer to your question would be "node gateway.js", this was ran after the ui was built.): 

node gateway.js
1586207099305|WARN|Starting...
1586207099322|WARN|MarketCap API is enabled
1586207099323|WARN|FxConverter API is enabled
1586207099323|WARN|poloniex exchange (poloniex) is enabled (public API)
1586207099323|WARN|bittrex exchange (bittrex) is enabled (public API & trading API)
1586207099323|WARN|binance exchange (binance) is enabled (public API)
1586207099323|WARN|kucoin exchange (kucoin) is enabled (public API)
1586207099324|WARN|okex exchange (okex) is enabled (public API)
1586207099324|WARN|UI is enabled
1586207099324|WARN|TickerMonitor is enabled
/home/luke/Downloads/crypto-exchanges-gateway-master/app/default-ccxt-client.js:44
    this.ccxt = new ccxt[ccxtExchangeId](ccxtExchangeOpt);
                ^

TypeError: ccxt[ccxtExchangeId] is not a constructor
    at new DefaultCcxtClient (/home/luke/Downloads/crypto-exchanges-gateway-master/app/default-ccxt-client.js:44:17)
    at new CcxtClient (/home/luke/Downloads/crypto-exchanges-gateway-master/app/exchanges/kucoin/ccxt-client.js:14:5)
    at new Exchange (/home/luke/Downloads/crypto-exchanges-gateway-master/app/exchanges/kucoin/exchange.js:61:18)
    at module.exports (/home/luke/Downloads/crypto-exchanges-gateway-master/app/exchanges/kucoin/routes.js:13:18)
    at /home/luke/Downloads/crypto-exchanges-gateway-master/app/routes/http/exchanges.js:38:18
    at /home/luke/Downloads/crypto-exchanges-gateway-master/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/home/luke/Downloads/crypto-exchanges-gateway-master/node_modules/lodash/lodash.js:2990:24)
    at /home/luke/Downloads/crypto-exchanges-gateway-master/node_modules/lodash/lodash.js:4874:18
    at Function.forEach (/home/luke/Downloads/crypto-exchanges-gateway-master/node_modules/lodash/lodash.js:9342:14)
    at module.exports (/home/luke/Downloads/crypto-exchanges-gateway-master/app/routes/http/exchanges.js:25:3)

**Comment by Luke-Small** [comment]
I checked out the source code in default-ccxt-client.js at the specified line, but I'm not experienced enough to detect the issue.

**Comment by aloysius-pgast** [comment]
Thanks. Can you also provide the nodejs version ?

**Comment by Luke-Small** [comment]
node -v
v8.10.0
 cat node_modules/ccxt/package.json | grep version
cat: node_modules/ccxt/package.json: No such file or directory

This is what I got.

**Comment by aloysius-pgast** [comment]
In ˋ/home/luke/Downloads/crypto-exchanges-gateway-master/node_modules` you should have a `ccxt` directory

**Comment by Luke-Small** [comment]
I have that

**Comment by Luke-Small** [comment]
sorry made a silly mistake, this is what it says when i run " cat ./node_modules/ccxt/package.json | grep version" 
"check-js-syntax": "pwd && eslint --version && eslint \"js/*.js\"",
"version": "1.25.72"

**Comment by aloysius-pgast** [comment]
Thanks. Did you update `ccxt` module manually ? The version referenced in `package.json` is `1.18.311` not `1.25.72`

**Comment by aloysius-pgast** [comment]
Closing since no feedback was provided
